---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 25.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    domain: test.kqmav.com
    default_redirection_url: https://auth.test.kqmav.com
    authentication_backend:
      ldap:
        enabled: true
        implementation: custom
        url: ldap://lldap-ldap.lldap.svc.cluster.local:3890
        base_dn: DC=test,DC=kqmav,DC=com
        username_attribute: uid
        additional_users_dn: ou=people
        users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (member={dn})
        group_name_attribute: cn
        mail_attribute: mail
        display_name_attribute: displayName
        user: uid=admin,ou=people,dc=test,dc=kqmav,dc=com
        plain_password: ${ADMIN_PASSWORD}
      file:
       enabled: false
    notifier:
      smtp:
        enabled: true
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL}
        plain_password: ${EMAIL_PASSWORD}
        sender: no-reply@kqmav.com
      filesystem:
        enabled: false
    access_control:
      rules:
        - domain:
          - "*.test.kqmav.com"
          - test.kqmav.com
          policy: one_factor
          subject: "group:lldap_admin"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - auth.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: auth.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
