apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:1lqeKk/jje4Uv2RCmoZ3hpWZIh/+SPhew1x/9Vbf+70hlYFd7FxteUMKxeurDrthQ+vXHQ4/SXn8J6rTzgpNJ6Y=,iv:tsPO55Odur6mN35Hxl1BExWjMdcsYf4Aeh8Brt9bCBQ=,tag:PxjVcy29Nlovp2GdZE1HIQ==,type:comment]
    #ENC[AES256_GCM,data:SeWIsy80kImDp5IgPRbA1zC30OC+41rWser/Qtvwyr8QqMbHmtxjK9CK3G4=,iv:ofkfnWScaxoUhyPnmYR0tWEsrndf3HixqEMfUzVIvWU=,tag:/FkKDDVa3G6SZ31pyNklmg==,type:comment]
    VIP: ENC[AES256_GCM,data:/9RrugVWnm+0Ue0=,iv:GW2IJTj2YIsgUVixo0p6TcBKGGes4IS1ycbFK2/6O1Q=,tag:Jc88o1hmRDaYonFDz+i2Og==,type:str]
    #ENC[AES256_GCM,data:q5eXoTkWBNQiMmvI9JhqX31DVTxG3kntmdz9,iv:QNF7X+ZpaxzKrno3lWz+zDo+99p3rrjpYkMm2vAvyuw=,tag:TaoABryjrFp292h0+Ol9uw==,type:comment]
    #ENC[AES256_GCM,data:zm0DdU96UN05hbJO4dLNUUSB5B9Sf9zCiuxQUvVXP6TkeMGUh/j2sr8E0fS+f8yTnroMVBjpbyGTUT7Nj3XJieQtuV3zmQtHkAYZIelUXpZma0duKsHPxOQ=,iv:M7hn/fjT2O13YG2Wfa2Pt2N6hBj0KSQs0LL8xRGIVAs=,tag:1bDD1hqRPHGjaC+Euxq6eg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:4mbkFsjHCIAY6eoa,iv:XNBHdiLhDWoM4Y0hQT4CD5OeMtgnka8X8aWSyyK+q2o=,tag:o3i2Uf83O91Cv27f/5c4WA==,type:str]
    #ENC[AES256_GCM,data:4DMBPVHOi6fkxETL3QOf0Y8TJxiVMEqXxLkXafGi5pnBIQ==,iv:uOeg6vE2bhHUMvr4lBL8ThXUkb8oSujDLcI/e4qf6AE=,tag:iLdfNeWCAgVBqLRAB0Oe2w==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:T0cVqjaOAX2exrs=,iv:+8Jiynyta9IZK2Q83ceAtUeL0mz1RUFUorYlPwCAqVc=,tag:/THMN3au0B2R3wWMBuJZaA==,type:str]
    #ENC[AES256_GCM,data:TC7nkpega01Rk0xIfD2PVfpT196lYmYJxuYKKtoztLO4N8vBCsrkoLVAw5eUxFA=,iv:cVwIvixWavvxuNYFn9LZYHqp5IWbFI5+H80kN7d496c=,tag:aIGQPUi8+H3DjgCtN2+fZQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:2IOeXZ4Q1JmfM1QLZwdABjukiVgL63rE/eteQw==,iv:qqrY9o8UKnbLglZpHOILfrwEz67iev3flfomI1iGxcY=,tag:RqzWVcTIA8Og5i5uJc3cUQ==,type:str]
    #ENC[AES256_GCM,data:H41wuF/6SlgGj2h4abPNsCTtzX+ooOcWTP94+H1FrDmHaaW4bkDrWVSxAaM+BGjkbPpnycOgR67QricAuci1cgbC0SzigI0XbWd17xhpb3tX1g==,iv:ag9ZBwTR4DHzSl8726xGFUIS7tyVbJ/PLH90fdbOBZs=,tag:J7ZuZxgbdxZIOb/zB0eG/Q==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:33NCwar8D4u4Sg40L4Y=,iv:S8fYaqM9DDzak8M7Z1H7p8yt+r5pN2X8+DWhuKakzrU=,tag:xxdCXlaGbHiOCiJeDWfK3Q==,type:str]
    #ENC[AES256_GCM,data:DJKLAI4xFUeX0MUk3EIqywi8d/9aLUC2hMHtzIW9+yBV,iv:Yedj6GmiY6KUHljTuHwpWcziITSAbwiru6zTMpP9B9g=,tag:QtE8J0p40CVAzQ7v23gD6g==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:snpLIvvvxQoC/NBgJMc=,iv:Hq/517XJGGr+jYSQKiJ9HcHQoWYPHvrDhBk/7s+6c3Q=,tag:MvbpVaPgHEUOTZKh33ijvw==,type:str]
    #ENC[AES256_GCM,data:nPDRQYDhTG5vmO1bNnntgXnCX21qjOYxl/UqyUB2PCsjEMJi68wSEnii/tEXCXTAWtPIe/I/uchi/ALwWlen/ifkXAnrA9yYjmZtQK4RReQ=,iv:DVsVc3aLPLBvH4GIBaKZcr9hH8vxKo3QA5qvxj67APg=,tag:9o+eLXonAFxEdIAH8vVt0g==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:C+H6E90cCvwamGt8aV8=,iv:koQdrrWtEZas1cmRMDJEyW8XU1gsdel9zQ5iDBHgj6A=,tag:4CAdq2IMcnaEvL8Tg1/0Cw==,type:str]
    #ENC[AES256_GCM,data:rjMvK9WQZTQ5eBzzYGqY801Ca3p59vKx143XwUXxvk14/TFDsTMWrCe3nkkoDqBA2kuc226DCxCJ2UZA+8RvbHFQvD5BsfOiirvj1P7v/aG/cHcBL6c7,iv:QhYYXXoSSIZqeLD/C1C1VBbR8mP64Bac3L1U9GNRK1Y=,tag:DqKcoSStinsowWf0+7+jhw==,type:comment]
    #ENC[AES256_GCM,data:OrybCz6WOK7urH8FV6IwWj038aEMRhDs6Lq11QZc6QsAha9NM749UnbbeCu41EdMWKZi9Fu+qbL9Z6+8KYdeufM8PRPsx204n6CpgOZNPUfeC6WiY3ONMll7UUU4ACyVcoVNNvzCx5q8QbA76/TugQJQo4UZExWmylHLQw==,iv:waucUYBwfvVAQ5kZPXXxOYOWP+upfcOTeoPMcj/76M8=,tag:tdYFSyHUeu74ulzW41oldA==,type:comment]
    #ENC[AES256_GCM,data:fd2fC6la42ALz1pwSG7z38Aj7yuP596NzUzgHq5pArgKs2bYeaVIOwJRAGbrvTsBVqbAPKmTgi6fcdTP10TP10aMXLaWV9dSuT4F7mULSVQ=,iv:c0oVicxLZ7q/UTtVhOVHmY62T8LeOAzb42GgcXY6pY0=,tag:ynfX8OFEZdRHeQAFNhJPjA==,type:comment]
    #ENC[AES256_GCM,data:8n+7j+CoH1sbszdoqUSQFEbmhcf0B8OOiR5YRPLVmsMPs7fAMguFlTXXiUpNqbNpooOg9mku,iv:a8e0yrol1V0x7lS9EhXlBAdE1OJqGIDNkHgthywW/lA=,tag:RJbapjI5FMf3uSkKoYZxsQ==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:Xoysk3qKhfe3SdEw3JQ=,iv:zJNVoKjLB8uZ7MySAX5tEeLEm5hOyMhAwBZFIroVQSU=,tag:SYYYRpm6OAno9OPiT9tNLw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:Dc8KHe+m9jyBgSH1dSi4Qb/PHB0=,iv:03OUc/yWtz8t6zpSpMG35WeRGevMg8ZXc5VQGIrq1bQ=,tag:Hcgd3POFX5WLpSr0VycYtw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:3UcOUi+mSpJKKyHznrv+nfAku5FmIJYuz32XkmW7K7slAU0FE1xU1w==,iv:rtPBEDaZ/Wl/1Nzx8it1CCSLUtRiEa0Z16ICTdOZ4yI=,tag:qKKtFpm4BRhCD79EkQZOyw==,type:str]
    #ENC[AES256_GCM,data:I5Gv1V8wLV8wl41wpgVXuJUENoKUcJhMy253P01GoFGoHhEAWF7wGRPXt/PyfSoUg2lzgRUIdH0=,iv:gz9J0LDzMsOXn9XVvjPiPsyp6+g0qXu4o5W8YCjd2pU=,tag:GCOWlmDEcaIRRz2NKyRGxQ==,type:comment]
    #ENC[AES256_GCM,data:jRENei3sHmCYOWg9Q6lONOsLXly8oWN3rA==,iv:VKPJ6qrIPbMi7uYbymYKKgKZySebZ23QuDXlACZ0wxM=,tag:pd7M0cRDpwaTAJcujpmj7w==,type:comment]
    #ENC[AES256_GCM,data:bzv67oMn6heRTk2I8bRWWXR1Q74ph5uI8DfR9yYZLMIyLBOCad2gAcTZutivW14KJrEdFaSbxbxEodIGKJKAaMkrnK7cTH6SE9O39v0=,iv:veMGA8JNG9FpUSKaRRegly7jR5+akUee7ClXo56vID4=,tag:jK15GSb7sUYcFS7oplUbew==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:yFG8duBL9FyrOpZT3ZNHl/P2LeQxEY/1uMQg0SzF+kW+edUU1gNPGnLr6LcEqi6q,iv:w7qGElK988KcAk+eghjb0VASiAtwWAMtgmfcJUcxhOk=,tag:WxnMFYX7zcMA3wIfSckBHw==,type:str]
    #ENC[AES256_GCM,data:L3zFNEWGpYYhbIHmHmD7nv5rjtFhkzESRIJ0reYiL3EnhUSZIQKrrQKR4c7nQ6tHelffymipBYVkFfO63nj4Fsk2IUBnApg=,iv:woJsdRSVOtytFsLIWIOXWXtFL06q3L1EOzkcTSzzKqM=,tag:TQTkleI2wtRzttmki88Ycg==,type:comment]
    #ENC[AES256_GCM,data:GAKLoVl50JrJbrBFmDnIJDQ5KJDbCc+X4rJ/rGeesQoEKM/bpt14lV25RQC2esqm0vnuOX8k,iv:BcRz42BNoK2QXqZyJY/y5WnerVTvwarLCd8wHpVWnbM=,tag:bwpvWp8dtjd4mITMcXvQNA==,type:comment]
    #ENC[AES256_GCM,data:y4SXl3JUwJvATF4LocDF6vsYxsB3ZDk889u5O7HZozT24EU=,iv:rvAKvkwIe6BRYGhlFDLIAqf1Q7n5sTYHQ6ea2sD5Kis=,tag:1xrzL5hJ/ZDq++Rf8aMNOQ==,type:comment]
    #ENC[AES256_GCM,data:2rBya5lUYM4U/9greSm8jCqp9hleBnj9BqUxor/zjulwXInfomna,iv:JGXFFmX7A4dC/Nb2T3lEWFVDLSkJDgi9znbMMkPA4zU=,tag:11d6xWmDFi0Zf49Bgyyq3Q==,type:comment]
    #ENC[AES256_GCM,data:IbKdkTMEJNpLTC/5xXs=,iv:rHTMQNCitIlr+nCB3bfEC2ELaaLNKlDbxUEPi8NxkYM=,tag:QzwMNTw85BP017Q6lkbjMA==,type:comment]
    PODNET: ENC[AES256_GCM,data:KHYH0pIBWxQFKcQ2Zw==,iv:ZSd32xAZDIzWl+eVrMVCyy7PI3/CxfSK4s2gqOn6eWU=,tag:bVjxvOYH1EN5afhksXU0yg==,type:str]
    SVCNET: ENC[AES256_GCM,data:87ryNzaKNtOwso9n6A==,iv:dqt/ph/3YXVU087vyn6VVNl0K09mUSBomvN90UMQuxI=,tag:BhnUmhuR9u9/jS0lP5QJZQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:o9iQ7w==,iv:+ytcD4NdwttEG25yYDMPyuzUBiP3bminJjsXcQdvTX8=,tag:PMLm81PBTo8Vpt2Clkz00A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOEJ5YXpsbDlxRlhzc3J3
            NThpYUNNQVBOUFhyc0h4WWZrYlhEeGxYS0RnCkw4cDY0MFZ5NmM0MFUzdVVQUnFL
            bTNnbHIwWTF0bXhXN0xLenBURlZBMUUKLS0tIDZVT2VCMVRUMEtiR052eTd2L1NR
            MTY1SHR5TU1sRWxWUHRGdEd3TkovZ28K83e/4vUgnOYKHDdJv1vEA5CE3/M7CaFo
            /QdQmLcSlzRygAJyISdc1xSjwWIl1VK6opVBuq+coCTrzU15hZmdiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T22:18:05Z"
    mac: ENC[AES256_GCM,data:Tgb01HOvL51Vvx5lTUYrbmOf/aIJjMvI8bOO8MRtQJMtf7gxseBkzEIFtbBo7/pXcm8m4JzXMpwWZ8/469lDrKFx6mgznHhxCqAomiJ/xGnHRIpNslHJoOIdZRjNpYZ5ajFDX9+RqRZT5a6di23fZ2n+NrNnp2GZOH6Bf2Wz9iM=,iv:ZU1trkf4B6MjyC3IS8S+Y4Zx7f1fFRZzzGwGMKJaiMU=,tag:4kljlKPY5RNFy/vXHxygSA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
