apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9AJRZejSMdcJj7zlOVjrNqRQ5CGPqDp0f9zFBwXm0j7k0rAHVPV3Me5F/9hyPduh1TSrbYznqjV5+vzYxCEhrsgkZ/+MrnaugysrsOymNAzjcQO1infg6SIILOpMCenP9bmnrDsM73JwryRvfH1egoHAPU07KP6DQ5+mvaNKQCwW3to8hw+KsXAMnYxN5//6C00sjun5UsQ3IBoUxo2YqQkDi9h2VcqwOoa34mdBNGsyaIf+LZhvohTPhWPaZKDs7KZY90Il9CStK+0oyA4nrHAOPK3g2rGg+LLwatySBGxw0Mc/md+RvcCdVY8kRXZooqNg+GzIS4aQBlaLzxtknjmzznNmoyEB5dvP6PMjMig2rSnWXZTfH5yOYE87b4qI,iv:63G9ikem6diWifLnd4vtOQ9it0zo6vkBl34Qu2aL6kI=,tag:iR887JsJ3dNQiueSRO2RPA==,type:str]
    identity.pub: ENC[AES256_GCM,data:WFtUxOfoP0nkSkywQm9xXPAia/0TxPWgiVltgoTFSmRmwwzSTwte/y2I9n0KXDYUjjqOYR41p7CBhtSEynzBXmkKcPe+JIxXPn77kw0zxy35ZWt042tElREwJbvfNTkGbnVTjYmCFGoYTOua5qmUj88yJPOrnBmUyw2YxzhYEm+hJxDr2TkHJ8r6RggZvpvJTyLuIokYFbOONPXeUu9kwbMgDjqTW91jl9TIUPy2v372PWB+I3wmsZ3xzBCFEbcnV4nY2f7OdZq3BvAqzg==,iv:xTqBbWhOJRITCVcSHN6BQbmy8txpPBg5Z3IFDl3SGdY=,tag:SSQvcWS9I/eiZWQ10cekPQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:/Jrb7Kehrx0TtExBkdUPLVUf0VfQYJqhg3IKSm6iY6LrLDDVxL6NpE67D4DdyUsTxvwqUi2RCrXkH3ROOtCS+55s1/fbCIo3DFief35cbICzHEMkFKOz7kZUFzZW1CHcwCZ5nBarH9V88cWE8X1hPMSNds6zHWc7paqdquQqrBngnFCTM4o4Z211+edhmUYlQbki+NPzJGr2kBPgg7WTtkHE9UyYv+WzZspJ,iv:oO30AaHX8kBjYJZy26ZUn60Omq6PFtNIPZaqkc9Afok=,tag:5x/JuZQbXKTvTRloca5D1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Nm5BK3NSMUdKRXRXTWlD
            TjNjRzBuU05rekY5ZDZVL0NRKzB6V2tvNVUwCjRhTnNUcWJ2MkVaZ1R4MWo4dFdW
            VVdaUTZKd3RlcmZMdmxvTDRlUW5qK2cKLS0tIDB0azY0VnJiY3RmUEdZaExkTFUx
            aWd5UFJ6cWFPWmo4RkdTNXhVaWpMcTAKl3ti+WDJk12JXjOjCidFHqwoRYDQRYxr
            hsynMYKoBn3LRvvru0JpwolaUtekkuE/dkPLfkGnPv3BVqGfV1Jg5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T15:49:51Z"
    mac: ENC[AES256_GCM,data:8r7ZGObeEQ7L+sVqqlLe8zz+gi2RDIueSaHgJte5F/6dEMZeB03Ziy8r3B6E467AQUX8U0KHdEXYDkXlHtmIGouB7Qjuzxjjthj0YkRPJ5JmKRAvbbHCZXf5Q5Mo+nM1EPt7pTJvKElFUYv22tQGg5e2V3yhBldb71dK/DX+L+4=,iv:09mG9VbtXkcmjHH/ldWX7CJDH6doBW9TYp341sUhSSg=,tag:V+c1ehoWeEqYW6pp0QjvaA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
