apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1821R+wz1thEQ5RxNQss3HOs7LiCZGe76iwkL7JB7QbPhuf3ya+wQ4dzSgQcZ3AOZb/RKsLqtUSfALI9mVwzdbwc1iTlDyFVhzNKgI++emSqQpfSyIXJJUp00zxCtFBC0S8/AcUMNLlg7Y3recST3QMOaOpnwmlqdSSMUU9ruURm6JgUursBKlEBUunFQ3zzZju1i10IuOIFU3WrIZUbQTLE5qyQ5rxtqB1JPWx4cXBuUuFwKq6UBtr3u0+J9bVwKHafVGRMnNFMaEdjBM0oTBBFUf7Jur0P5Y51pBuJpvlmGaaU+MO2KYX3uP/NR9pkcH4PWL5hzF/FEFvX94SYGolR1An5wfSP8Xktt+h+mHb8fMT/rgPOt2nboS8AHXsI,iv:dHukSqtf4Ou1Ea2zkYe1SvlkFHL/Jf9U3ys4zxOVO4Q=,tag:14sEssY8361fG82t/vPJLw==,type:str]
    identity.pub: ENC[AES256_GCM,data:T+9H4WjuCnvdjus9EBKZYyywsMWgbx1BX5Y2xzr3AnGeqP6Tjoh+ZxsdULTkam7L54j6/r3E85mzKC5TIj8zscxHq27hiRFhUBuXJ06HpU7tpJRZNHPPea8tjmKNf+rJ6EzNxX8RlT2CyqHuRQMee8uR5t/+g58zzAw0E34Y3ozBo1xBici/sKsC17PL22Iyod+GTyy/V4IFs8GZdD4O6aCpHhlaiLuNIqKZVuGMwXjWhGmTBO6V1w7v1JyRmA5OijG4IUbVST5ChqoXgg==,iv:qWOZg7SnO+emLiGhHVhuRloKLnS9xcRWNOnbmIyWCyk=,tag:TUsmJNHj4+WsqMCuu6QPpQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:DyiAtQjfsHYso9bNmWL/4hqFZxAmgmqQw01k1XLY5nF93HvKvy9gXaBDrppE5IR2NHxV9YhdflaW1jzlV60f8J12u/po9N32nYv66Q8D4HfiWO0PLXaWlLqp+O0KL+cXQFbinSo13VNGQSnA0Am238JLg/qeOUhmIvrxmkXeGA/HEXRWXYwqPUi1SzO1tEtHRvw/54of+brpHykUVEe5Rkn7aDMwFbNN6jOh,iv:/u8j3WaXzIh0pRVnJ3ckiBnhfv/PXIOmftsqRcAuGuU=,tag:+RgB6vPb77eoH9vO75rPMg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXl3YU9zUXhBWVB0N3Aw
            TmdXSVAxUEREeFArbjVBTGgxais4Z3o4VFg4CkxCb2xjK0NGcmFkQTMrN0FEdGxi
            THE2aUZESlp5dFg0NEVGbDNtN2ZvdTAKLS0tIEltNXJMRWZEdEROQ3RrYU9JUWlU
            bDdwRi9TWW9Pd0Z0ZmlwZ01LUGFwOW8KB30aZu6t7bViYsIb4WksZT8l92ImaF7D
            FeyRSpDzKeLzFsvwvc3Y4+efNPbjejL4/d89/LYufkcRWjqtbqbRUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T23:24:57Z"
    mac: ENC[AES256_GCM,data:elz1+Q1f2i/i/aGNrAyJc3AC9iTEB51ghaeKtfslYO25BPv2beQAsA6YjgsKKQ1nQWkQks2h5cPcogowlyzBkwm9TFZvTPAlMn5fnL1PpzZASpXchIl5nQ6P18NAeqS3LNgKosB5xKwB7cxkt8TzdW0ULLPti45GDhPlA4SEA4Y=,iv:+wPs4OFP3gyLzKp2yRCU5wcmBtO5Ut866kQD5iX/zPY=,tag:OhE7WZVQzWqyz60xcb9jyQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
