apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FQH8GZXW4QgzMpeNrI9tWpneBNpp130ShGeXmqskbjFeuKw+ul378m7EsLCXACf86PUms8KbgOIaIduQgSMq+98iLgQQUxMh3WouJxVSmeuvZKlxB8N+wxTdfGytO07mAhxFD5AWXZETCpMckEys0maxjc14jITxZBsNIwXfpJrycvfDVewD5QriQW+LOua0G3CBfXIsPWqoPV1OU5WPfe8HIsP/31zwyE0/4FRXftJf+P1tyYofVpG74fRG+2n+wAfePEHW7TzZrrCJj4+Mll8beuG2ua6XZuMvhMiDxW9q8tnSgU4R8b1lhOScy7TuEhNLSQ6zRQdWBata1GjWZGsmsrk4/f2Pe5/86V4X3mvXoUBI8hgpll2utvY4aPhw,iv:NLffUpQNlT7a6QeKn7747Gp+ay59B734V2wbfigiL0M=,tag:JT1EYNg6VQ4sAuVKlAZ5ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:coVVx+4FT0YmO/HJRDAW50d8711aH5nz8q2OBhinoCaVKyzwdB94JVowWKrYwAvQC8UoHeLz/cXI17yxc47g1RGYxHKmIEtgz0SW+8kX9Q13OkUIuBenYZEBroYGUNNu+xUwvJ79W4Fjgodha11QT17P19uzQS62gIt9f++c4jfTatF8vSqKzSEwYYGhsD2V43bW8EhRMg/26JZp5GrGrSpMJ9DnpFH1PnQMPhPLgJsiBScJvO0CtEiLtzrkEkOFu+cl7pelQisM3tksNA==,iv:E1SKP+Vxshl0c8UWxkq81WdIeRy9uQPFb/RWOrMglDI=,tag:5Vj8KXgOFWiAVWBwYgmHig==,type:str]
    known_hosts: ENC[AES256_GCM,data:wKLCdP/sRG5QZ3xZo7c3PJtcdtDGVevxZLpmzJnsi67oGM4VtOSuRRoP4UkvlmVRcC2ota42jOmRR1ob8QNwIW0HO53CtxUmpguJWJi5Gb2aB6a0zALMMbG4kxio8y01yO5PKg+ju5CFT5dQS3pYaN6IRstwEme+HS2YEdHgbYIPycNFUVfPGB8OM5bgpc6FPRnFNaNct9nbeSCBTt3nIeM2SyJOUQtI9uA6,iv:S6jnZgzNv7WWkdxIugGWfNUt4oVtRYEJodueX8yby5o=,tag:tQ0imoTrUwkBcP0kB+XVBw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaW5yaDdXTUdvSTFRTjAz
            Rkx6QThLR3R5d0hwNTlNNUpuZG4zczdPcXlvClB0cys3eXBucG9CQVFxWnlTUVQ3
            dlI0bXZ3cWlxQjA0b1JYMHJ2WjFULzAKLS0tIFlPQUJzMHBrUzQra1ExRGs2KzRu
            aGcvUHRhK2dwL043VUxtVW8wK3VLZmsK84MUcPxcbjNzS0zAcMdRmOjYxc49QQvC
            g0XcDeofkQNjCJ+c2RSILhhSksSjTGD4LA/0MMpBw5idPDO6CxlV3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T13:55:30Z"
    mac: ENC[AES256_GCM,data:MTiM/gityR1xKsxnbGsf1CEBjH2KNzLnKPl4tkyAzvHT59m3YkpqZ0K9/jAEueHswh7DkLHCCvFX1az88mWSuR6+W5CVaPmRmMbGPdWE8r64ueXOgXvR4+LO0kqLJZLfTifmDHHqrsOei5rwmB+W4YeG25I5g2qPf0hBB2iD8j0=,iv:ZSeLFbHCwq0yq1RaP6cfFybSSKbCJ4owyC2bdje5j2I=,tag:SJ6k0/505Pnmk8z9v6FjfQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
