apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:m0EBikgKHbmV9sKVn7ebg/6/vEsXpyrsUZdgNn0slstnxU9kq+SqFwdfiugtTAZ+CdrwUQnE57D6RDNGzb2OQXAYesernHYP1QMgmF1WyrPLZD9+CuG1xqa7jfBXXb8cqlz4rZmHvUOIyEoHJsdJKWozmRg2dOrAya6Iwin58+y2H75VyY8lZ96TuPKu5qfKrq10JpFecgI5Zby9I/w/HS2wbs0ZgSeXLYZNlWgDw2y34hJxMeFhFvZlE+HxIkPw0QA7dGnTrlX0nF3Q/GEZub0Cugx15vDFX27V7uXJQ5rJZeJWQYAPnoKblGa3WPqfEl8FwFRaAOgHN4h4ltYsEC3kU/g/hThZwVKGImYYrqqhQbSaddg0zYb549Ty9lNF,iv:3Z4gHvkOBP1T0oWv5JukHxW7+7xtTpsj8+1LR+eCO8M=,tag:N5vbnmBy/bpKTmjrZ+k9dg==,type:str]
    identity.pub: ENC[AES256_GCM,data:3jtKk7oyx23f8fwcsuYVH6uEQBtHuMLjw1W60FcSHnBKFdiGPf650OrQpXm6mVfslNty49vaOgagSvaxZZooTGq89jrf7fsJJB+wX4RIJMRybmpbk0JnAGYVvly84fzL6owOrCiYWX+jorCLjwHCh1bgExphzV8vWQuY97MeKwijBi37TYvEAvvSNaS1ewJDp0L69qX7mu9NSVo5UvcDTE9yCezpq4CKK9rwoqC2trS21PqCgWiLF8RA5YZp+Tqa5NuGP6HN+o02VCJKGA==,iv:OY9JoY1vfHvU0B74+a6UcIxndf75kpFJ9OR937DXEhc=,tag:xpDOrid8gMxjXOk0krW8Sg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ExjbXZKS2ltryI1PaNQqbszrQJxEbV2UTDWQVy3Cd8n09E2/191ERMHp2nK8pVm2dJzpxRPyfBmBa/I2orjluoBzawr5N450PZZ+aHrvKU1a63YFGgPz79Lzof4eNBRErvKkvpudqMjkxthLE9uSd7jG+plIBk6sJ1NY5ZXbXWNpD+0HS69Q/9A0MsC/faFqSrXHT3eLFDGmzn5Af24QHfzVrCXGeszOd4cc,iv:85/MKSO6uv/qAnMQt0VLJCMsL1KesO/9QjIF6j7Fd8U=,tag:Ib0I9GFmiFZtQvhuRcEUog==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VE9uVUJNWCtXeHNncTlO
            cTZQbnpvVEVmalNKb29obUsrajJXTjZYTmxBCkpwRGZnYjNuRk9KUHdTRHlscGFj
            NjhFVlUrZWY2NC9YbVl3ZThDWUlQYVUKLS0tIDZnTEUwZGxGOWx6Y2wxNHN3TXhK
            VVNSQ3NnWmhxQVF1MGtlT3UvdE84cXMKqRLbTt4uCRjaKrVDMRWcnQRp+ai8XqhY
            KCEflRvOdd2MKCR0LyiLpi0EwIal/VBswicwnD+LC3KC05jjW9xPzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T14:09:29Z"
    mac: ENC[AES256_GCM,data:UPWYbSE74Wn4LtrTzpCEjzu8KZ/ADo+dKz9MKSF89itHzZ8ys1mlUP7DJWL46hnDj1y5aC34CPNQtnDVbDxArO/qzYG7HtvVhNnK+VO6BmvZaVRHg/5xlk9EbizUt+fI/zx7z1WXEeDDgLb2q0jHFg1Tr5XQP8067Jte3ieCrSE=,iv:2QBaWLBUACSgJzJhELzPmBRwou+MRmn0Rzd6xJgk1/I=,tag:ns24Ai+yXSX/n4Wn5XzeJg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
