apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9Sm0ZkxmRSlTY+EVDex+UQw5iGtbzPNvy+D2Gmh1Bo7lkhoHhwvh0htsxQbgavZZ7YzVOBNYBhk7Jg23guk+XdfRe2pKhEns+kQxVhF8PhBI0oKBEb2aUhFjgil0/vqdFr5FQP7A9N2g2SmSql4vHKhrGvD8ZmtMFRFMdeVAy6Etm+Was3WygFyVXSnw6WE0Y5iwqRN1TKjtlQpmW1tf3NW6vHByzmEhEb9G3X/RuuuP3yOGrOWNrGX7B9nkMWBSR9WENLvqq24MYiKgNjZdLO/uNSFg1ynauDn1Q9Qh3WG2yuyLf1L79dvlGskH8KiMfEe+kZw0lfdFMDcuVGLsXEjTQnpMWhFm3iMkVxP8b1+vWLaGtJAS3e2x5h2AalOv,iv:gw5SNEeMjxJWLzDLUiNxwp7aagUlTe5xPZSyDOMUnus=,tag:XN4iIda8e+LBnCxLFLcJrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:WwEjTO3aOFMBCDnc6JSBYQoJ2+KjN/qVYdkynWZ51S5c7iNY1cNx4UYVPN/X5CXd6r7+0p/tajBavkOAZvuWrwfr/VSdMGF/2cYK+YibjeFffkRZ/m/jzIMQYXT3AIhfgrbw9HWf8KiAGAiIEaDY37LlM4rUaHn2JCJ5mQTOgpcb1L567qpyzOzKP+plHX/RYEkuRrRwlp4tCa4q4PG310iBAN9K1xf9DdrfjliA77OqYEg4VGVcFViQS59BGBbLYdGKscjQYHBbbRYaQA==,iv:J/HaFoLAc5CCJQT8+fF72p0Quc5G8EJDylontEc0jBA=,tag:BlWvfyRi8Cpq9S1BWPVphw==,type:str]
    known_hosts: ENC[AES256_GCM,data:E9I4pApXkg2oA6hUYW69PJ1nNsn95gZM8KB8TLLxcWktl7WWADget7Vc5L5iBB7Kxl6ox7YMD8y+pJ2Mx8cMo42uVxxtrvgiRHqnXMJ5aJx6V60jZNremmJlsFYL+4o9Kl52fIsv/Fl9LRYu4TqsfkXxR2t1IxzDG1/Q2TJzdh2hjOwUhKrtqalaXsDpwGPhEiHqRREydsVnissiXOK4Zn1ELWeS6Ws+a+Za,iv:gyLKqAKSarjs3LKztAuABnyzBnOh/TljTQt6d+PJoOo=,tag:6zCbWhWyWQrRh3nadOyHkA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0JpaExod0kxckVqY2Mv
            NVhLQVozRVluSHhoSlpmT0pMN3picDVQZmlzCmxWODRWcXk4UFhyTElKTk5SOW5n
            SXgrK2QxcTFTV0szWTZ4VTBQY2VQZVUKLS0tIEpiQkVzRllNT1NYcGxSOXZZR2lY
            cXB2dU9hNGNFcWY2ZENqdVJ1cFBxejQKTFtRBVcOBejfFHzty1G1/O7xlf+jQ679
            QMp97KNdSKZeOYIBbx293gpukaIx4veYzJLrYkUs22UZQQUP5HycKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T16:27:09Z"
    mac: ENC[AES256_GCM,data:/ITCxD+fC/Ymb5u+wETSnPfCWlvhz8+OkLGTYilMOLmLOGNJhLtrSv1GTwzwaPLP7uHcsqhJaMonbr821/LeOmn51lcgjAJl+W9kXGIqEGP7GGbmjub/MaO+TmGL22naoh3f5nDghFy2fWerboi4zkbqg2fUJ3J5xRdiLB2pgSA=,iv:UabGCMHTmthBJuVHfjCfSS1DOWwqn1eYS1nQi5diCz4=,tag:UdMnEgTOQ7S8WfLK45hkpQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
