apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JUFL6wfiDPDoibdqShpo8aSQAl7zSgiFI8vT3c3GQpu8t22n2i9Ki8W67C7yFzOheRCdS+5ncpCpzUWfY/9USeoCS+3JIUU6rI4nbZFNcGI2P5WHrc/KuHc+knWvx1pRzPDceSpAzCEjRj21y9CpYUcX6h/QuhvJhip2Mkrvpw0tD2UgAN1/FO6goVBj504E2YgwTLta5gX7EonTuX3h1zB6aZDbzm+10rXgK+niT7CWS2VNCK8fMt5XhWsEmz0/K4Zj+IcS9LNwDksI0bPOqkK8w5t/9xPGVCzNDkJDgH4WHNmJp4W+LEX4yxyG5LGmV9hwGezlNtLv4fs9r6Tlbz6GsYefzw1rMgJF2fBbvDUuLkDc687VaLgHPGBlDCkR,iv:8hTLEezp23JGIRbQRrkqT8FdraQfvQA0ku+RtsbsXaU=,tag:kQK6fV1onhsruqq4gmkJ+g==,type:str]
    identity.pub: ENC[AES256_GCM,data:DbFNjhMKFv+uKmctgZEanTV4sUCRDCNj0n12eLhEc0r6YlreFrWe9Bk2yFoxJr3LzUY6dtYKGhq2Lfw/yjfc3B4txaxNkqzP6a1dhPuRh33EwzcEfFYAaHlF0TTVLycYsJ8AHkRlmkGHpzmbI+0vPn6RZMXUHNLkrTUNVmmht4Y69Ge+zAE518pXeaJuFqgdpmNq/rbFpue3QoEXeCeq1oAvDO/+4h1qBb0QoAKAaNqwgl+sQn5GTQQDMl3UdGtNRRTbb/OSogVBi/zgZA==,iv:ye7D/U7vFGpy5OUH7BfR5YS0frgTDUXsXVrHMKhf7FM=,tag:8WctQfnrgBhPm/6m4A8+oA==,type:str]
    known_hosts: ENC[AES256_GCM,data:evgf51GjbnkSVNj9aX991JWVLCI/goAGQ3MkttbzmJwC+6Mq9eeviPUW52wjRUMlYNM+/TkGenMv/yiPyU7NPcgGngPxNCWA3fnu0ECI8JQWKSraAPogJ0J96GIybIaZxP4UckY9nn8vAU7DZZn8STtO0RP1zUzRXWTVb8QXwBtMwktvCV4RpT9P4jCguK3SxfeIrJPVDLScROYupXtzWuS5Ss8HlUajrI8x,iv:WlZQh/RM4ag+AHIUv+uTt2xwIJnihbupnFmfgnWt6jk=,tag:Y+a+kT6z2Hqt6GiCflU4Gw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1pqn7cvgl50pgcnwul2pwhhxjz4xmwtqd5lwsl47r6a45rqc6s5cs2tjt2r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZi9USXozeEhOQVpQcXgw
            dDJmMGYxemVHVHk0SDJEY2lRdXZKeU0rb1E4ClhRRHI3SHVBSSswc0JpSnBDKzBW
            QWt2aTFNZmJMTXZHZEZ6dDRCZ1d4ckkKLS0tIERwdlNVNFBIZmdWN25ZbStSMVU2
            d0FScTQ3REhwd1JzSjZRWWpEcHUrVTgK7FE6V6ETVCHiRz49/yjyXavSolDrCoGv
            Vsb9bm55kCXkinYEtJjrciH5ORa1IRtvBtWD2FQV+W8Ztlv068dMWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T23:35:54Z"
    mac: ENC[AES256_GCM,data:zq2YMuqxbGgvVpXdJYsBhdC22z+nnW4C75B57kV7GWctNSVws8HZUA3zTCYGTeul/eW0FZfHUZ8BYOx0QrHUPCL7G1Dr4S3eFoFFBXPayYDpW1VGkuXeLIeMsER3mY2d6TETk/mT9q3UgCay31t+BteQFD8yKToXapC+VizHvWI=,iv:TG9CpCNv9k2X9ob/sQ6qbKCYUJbCRqrux1zd3THNlpA=,tag:N/+Npf0hCxN6u3p6V2MobA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
