apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TFZl0j6vJ881Vf368Izyc2H+wvLtjqjxTcJ5DL5s6MCAJN4tX4Z1I30N6vr+Cve0ZKk7WUpGPJSJc/GoUpweZrYBsMHcrZUt+aIhv0f3iYINMxAlePE/4JhIrC9//HwEjT7HlM0KsVTUtYgQPUAXE8A12dfZTJy7g74vdqfnEru3u54tTEbZn6TXxuhDgxWN1MiiLNXKLbEEuftJF5YUNVJ0mkdiqUPck+GeEa1eDSJSBVlXfHuv/KQwqvg3LxZ0NXv8jnUDIc8fhKjhYxpMEQ+RhheR9ZMR2J6CzqtLThm6cC9BauMoUm7Hg5jhgwwdcWfyEmr8cOym1ePGbOaHPO+UPiub5JdpUwfufOMwMR2f7GBuLmTHnZrF1h+sk0lw,iv:QvJT5BQ+PP4vMFMqG8lHv7KcDOpacuFQID8+dr5KQPo=,tag:se3y1Rm4Y+w9v91lTuD6uA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tFRxKt8YKx4kj+c1R1MHTIjJjeaBUTFB/dlfD+9ZM2dYoOgCu00yfYN117/SDXzB7+rqpCPd0g9NNVvZT1S9XvLMNcACKN7uHC71oZZwHnZhxYzMUhxRnSuwjU6FAztK0YYe9u4t0coTDQ72DG44r+KpqflL87suTpMinVoGXEM7i/6/eW4iTCr2f2+yytLpH4HpuCahv8xtZ8H95yP1At7xY9ERzMMPchsgXHpkExmbG8eU7s+ts82EkQZp2HlcIGxhlbmXEAIKNBd/cw==,iv:+6KwS5f7enDJmehvcpT4AlG25E4CmAYW6cuQnMCxhR0=,tag:v5xT5UD8TtLM0Q2V+aIjeQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:o/xFpCp+u/j7z8jqz2QFIEO7QhegwxE10VSm2sGC1LhwkgSD5JlWEZbDHFuTRijjQHLp0vDg7+u3VlKglP9lhUo/pxO0maAytOCWUgzJPQVF8tDid+GikyqKsqUcAr1SIHYUDAwCQNPHL7Tr1zeU3q/kGGtm7J2Eskm4nVdLnGocXEpknNzn41rifePc3xJZEE6LtFbVXPmcsKLJMXGJNSkiODF4xoKPcoOI,iv:DWZFQxokDmMMJVrTsKKlAlRGWdSywZ3jSkQE2PLG5zo=,tag:fxYpAp5mGw90pB3y9yybzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1pqn7cvgl50pgcnwul2pwhhxjz4xmwtqd5lwsl47r6a45rqc6s5cs2tjt2r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUzliQnJUR1hMTURJMjZ5
            MFJDVU5iaGx4MEdJeXl0QjRsTHM0U2MrYlNnCjFJbTZqd3oveEM1K2FIMnIwOUdz
            bzVtRzd4QnI3SDRkczJuVldsODNUQ28KLS0tIGR6R3hsOUdoNXJXTXVuOEQxV3A3
            M05BMVc3Wm5BRS9IK3k2YXRGREhRRzgKa0eCzVEXEU9kMDX+QuKKtHCP0uBy2f9K
            2tJPR96ondv/3CLNJcYo3Vxt/DavANKHD63riMWRGrygQNGuuMZajQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T23:46:25Z"
    mac: ENC[AES256_GCM,data:zNq27X7VmYnRj0TpqaPd/RfNtdn0wVo0xejp5RypUdpAnQCeP3A3elMdFvvCrysI/f2ue1PGQD0v0TSA6SW+5SJd580ivauJDZyIdzzse+SLt43MVo96xU5xYayz2RAr/Qg5iG1WHW3uRj6fD6V22bK3YqjoeMjaVfn5vW3GpcA=,iv:DtzDyO48opJCOw7lNodsLva05A6cAEO/wnsA3l4IILI=,tag:WEQi3tf0W0X0pHqr7nqMGg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
