apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:A/s8NWQ0AVlpRQ+WJV9aibjTJToQEgVF/O6/PVfYSgrizgGKO8EXzsz6UItYcOKBCsDQjsO2OjEL6TJwOMXDWqVp7PYI1m5VOd561j5PPQ3BlFH8aQ0JOGS6pduIznAp3F80p2uLJQFIeg6cqsbgqtl7zK3V4fvPOkDxIExo5zYvbWl8x/2yyPCKxPZ4jqR2rDgsNRVWC6WSlqELf/i8vY00ehxj4/Sy6YASRxwhDuNFLUxkBfASK7s7AEKigEQV91zYMb4m0hNLNaWEtv+2obWbSuN/PWRwZAFTbJ2IyiyfLxhM3R7eriR4piKcLczsD4W+CgkkndazkD8yDfdUM6V0/DZA8+lBGrvu5VTlSnu5bJB25JF3Ox7Hfqur8p1J,iv:bDumwgD9ybY7PNfITux3QfmNSDiz/ChCdeE/n2erjv4=,tag:fWjlBul5YOVzYHWeUI4YGw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Q7ENRD1G+NBkjjgRjGDEkLgxZWl/mVc8doz2mxC7n9AsYoJGVc72tQefTgmWvbqke89/c5KKwTvbsQmHmwjK/eO3Cng6tTr2ILkFzQtvLjXKqhvW8jxiEBMBbQG58+fdMqM3l0T57ipEPvOoikwXCJRSXqaj9TUxOpTpSG40oqv0biaRcUqGrzcQ9DING9E+bZAReFYECufnLibbH6pIybdPAy0HRM+kXgxSan1VA1/iUhG7AmDO0cQqJTO6YifxICApMDjvR36Jg9tEng==,iv:XcrC5YFsEpTj7Z5FJq4OcZrmleKTEQEQmgJ1czi5k6c=,tag:AeY2VsCLjHdXiZ5778axmA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zV2gfLMYrS0buS25BYliNkSX6t1rw7VwFvDV1xq6vbuIdEOrKafZ9Ccxl/C1biBXml3doQsgti87PGGvAH96Hb7peEh+d4Vjdy5nPEUPtbWL+uGIqKEhgh8Xh85iOysgd48lrwWZqNTgyVHLzIYN8GJAjtpAU2dnh5v0+4sfw2kyQkD5PWMkaSc6F/OQgBvVN83nYfdrdXqzg4N6XejeQcvF5IBq4xNv4ki0,iv:oFrJ+S+xOz1BdwowJMVm5D2dnaNqLzAx2szb9PSNJME=,tag:tN8scc5G8pG9L3NwwrvM7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age163w26sq05nu7dk7u9vnvfjydtrvjmsww7yu424f98f6zsw6hxuksy9y7d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUGNXSWs5bUdnNW9PMkRP
            ekJOQ1duLytMbFczU2RwVFh3NUxEanNJUVNVClA2dzhwaENIbGpWcFg3TXhIKy9K
            SDczdERRT2pkMXpwQnVWN1Nta3orWkEKLS0tIDFIdFNUeXc3cE5DOVByeTh4U2dv
            NUJteHcvalFpempRTVdsZmFaaGhES3cKOYFw1n8cEvtb3TOrvKS1uv+LVxdgKUan
            ojjc+uwkuR3lvBGk8cKM7GxZL+Lsw+h9/0ndI1tm8TkncoQKEIN5Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-29T22:55:59Z"
    mac: ENC[AES256_GCM,data:g1+SU6wdgfLibWLnoBJPP/GeQEYANfiDlg1g92AYy4xnoN/PDZ7BK4VGzFIrHPVcIs5WWAe8ntnPeWs9i1OQJQNqKKgW/He8a+0ghrd10qZCeHheh1/+Y9U168iippwH4f9Bdv1YQH9R5wshZMVJqR0s6L3SYEwpHI1hPxEm5sg=,iv:9Wqin+vrgUai+m6bQcIebzxFzTUiEZLUTqAapAbVHVA=,tag:UouqskjIir2eMR3SM4htzw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
