apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: nextcloud
      version: 33.0.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    nextcloud:
      credentials:
        initialAdminUser: ${ADMIN}
        initialAdminPassword: ${ADMIN_PASSWORD}
      general:
        default_phone_region: US
        accessIP: ${NGINX_INTERNAL_IP}
      collabora:
        enabled: true
        username: ${ADMIN}
        password: ${ADMIN_PASSWORD}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
        tls:
          - hosts:
              - nextcloud.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: nextcloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
