---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 33.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nextcloud:
      credentials:
        initialAdminUser: ${ADMIN}
        initialAdminPassword: ${ADMIN_PASSWORD}
      general:
        default_phone_region: US
        accessIP: ${NGINX_INTERNAL_IP}
      collabora:
        enabled: true
        username: ${ADMIN}
        password: ${ADMIN_PASSWORD}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
        hosts:
          - host: nextcloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - nextcloud.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
