apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: homepage
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          traefik:
            enabled: false
        hosts:
          - host: ${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - ${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: internal
          integrations:
            traefik:
              enabled: false
          tls:
            - hosts:
                - homepage-cs.${DOMAIN_0}
              clusterIssuer: domain-0-wildcard
          hosts:
            - host: homepage-cs.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: ${DOMAIN_0}
