---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 18.16.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PROWLARR__AUTH__METHOD: external
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: internal-only
              - name: auth
        tls:
          - hosts:
              - prowlarr.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: prowlarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix