---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 7.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LLDAP_LDAP_BASE_DN: "dc=test,dc=kqmav,dc=com"
                LLDAP_LDAP_USER_DN: ${ADMIN}
                LLDAP_LDAP_USER_EMAIL: ${EMAIL}
                LLDAP_LDAP_USER_PASS: ${ADMIN_PASSWORD}
                LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
                LLDAP_SMTP_OPTIONS__SERVER: smtp.gmail.com
                LLDAP_SMTP_OPTIONS__PORT: 587
                LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "STARTTLS"
                LLDAP_SMTP_OPTIONS__USER: ${EMAIL}
                LLDAP_SMTP_OPTIONS__PASSWORD: ${EMAIL_PASSWORD}
                LLDAP_SMTP_OPTIONS__FROM: "LLDAP Admin <no-reply@kqmav.com>"
                LLDAP_SMTP_OPTIONS__REPLY_TO: "Do not reply <no-reply@kqmav.com>"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - lldap.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: lldap.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
