---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - traefik.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    middlewares:
      forwardAuth:
        - name: auth
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.test.kqmav.com/
          authResponseHeaders: 
            - Remote-User
            - Remote-Group
            - Remote-Name
            - Remote-Email
          trustForwardHeader: true
      ipWhiteList:
        - name: internal-only
          sourceRange:
            - 10.0.0.0/8
            - 172.1.0.0/12
            - 192.168.0.0/16
