---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.6.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    plex:
      # User Defined
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "https://192.168.0.13:32400,http://192.168.0.13:32400,http://plex.test.kqmav.com:32400,,https://plex.test.kqmav.com"
      disableGDM: true
      requireHTTPS: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - plex.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: plex.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/Storage/Storage
        mountPath: /Storage
        server: 192.168.0.2